import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import LoginButton from './components/LoginButton'
import { authOptions } from './api/auth/[...nextauth]/route'
import { getServerSession } from 'next-auth'
import { redirect } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function layout({ children }) {
  const userInfo = await getServerSession(authOptions)

  if (!userInfo) {
    redirect('/api/auth/signin')
  }

  return (
    <html lang='ko'>
      <body className={inter.className}>
        <div className='navbar'>
          <Link href='/' className='logo'>
            🥒 Cukehaterforum
          </Link>
          <div>
            <Link href='/list'>List</Link>
            <Link href='/write'>Write</Link>
            {!userInfo && (
              <Link href='/register'>
                <button type='button'>회원가입</button>
              </Link>
            )}
            <LoginButton userInfo={userInfo} />
          </div>
        </div>
        {children}
      </body>
    </html>
  )
}
